# Generated by Django 4.2.7 on 2024-02-14 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('application_type', models.CharField(choices=[('ollama', 'Ollama'), ('stable_diffusion', 'Stable Diffusion'), ('mimic3', 'Mimic3')], max_length=20)),
                ('exit_port', models.IntegerField()),
            ],
        ),
    ]
