# Generated by Django 4.2.7 on 2024-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='entry_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='application_type',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('stable_diffusion', 'Stable Diffusion'), ('mimic3', 'Mimic3'), ('custom', 'Custom')], max_length=20),
        ),
    ]
