# Generated by Django 4.2.7 on 2024-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_entry_port_alter_node_application_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='entry_port',
            field=models.IntegerField(),
        ),
    ]
