# Generated by Django 5.0.2 on 2024-02-21 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_alter_node_pubkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='pubkey',
        ),
        migrations.AddField(
            model_name='publickey',
            name='node',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pubkey', to='nodes.node'),
            preserve_default=False,
        ),
    ]
