# Generated by Django 5.0.2 on 2024-02-21 13:37

import django.db.models.deletion
import nodes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_remove_node_pubkey_publickey_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publickey',
            name='key',
            field=models.TextField(blank=True, null=True, validators=[nodes.models.validate_ssh_public_key]),
        ),
    ]
