# Generated by Django 5.0.2 on 2024-02-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_alter_node_entry_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
