# Generated by Django 5.0.2 on 2024-02-21 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_node_owner_alter_publickey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='template',
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='nodes.node')),
            ],
        ),
    ]
