# Generated by Django 5.0.2 on 2024-02-22 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_remove_node_template_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='template',
            new_name='html',
        ),
        migrations.RemoveField(
            model_name='template',
            name='node',
        ),
        migrations.AddField(
            model_name='node',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='nodes.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='yeet', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
