# Generated by Django 5.0.2 on 2024-02-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_node_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_domain_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='os_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='port_app_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='site_route_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
