# Generated by Django 5.0.2 on 2024-02-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_rename_template_template_html_remove_template_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='hostname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
