# Generated by Django 5.0.2 on 2024-02-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_node_node_domain_id_node_os_user_id_node_port_app_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
