# Generated by Django 5.0.2 on 2024-02-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_node_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
