# Generated by Django 5.0.2 on 2024-02-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_alter_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='exit_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
