# Generated by Django 5.0.2 on 2024-02-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_alter_node_exit_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='error_logs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
