# Generated by Django 5.0.2 on 2024-02-25 20:23

import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_node_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='key',
            field=models.TextField(validators=[nodes.models.validate_ssh_public_key]),
        ),
    ]
