# Generated by Django 5.0.2 on 2024-02-27 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_alter_publickey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(help_text='Enter a name (lowercase and underscores only).', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must be in lowercase and underscores only', regex='^[a-z_]*$')]),
        ),
    ]
