# Generated by Django 5.0.2 on 2024-02-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_node_error_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
