# Generated by Django 5.0.2 on 2024-02-18 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_alter_node_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='entry_port',
        ),
        migrations.RemoveField(
            model_name='node',
            name='exit_port',
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('port_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(8000)])),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='nodes.node')),
            ],
        ),
    ]
