# Generated by Django 5.0.2 on 2024-02-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0011_alter_node_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='access_token',
        ),
    ]
