# Generated by Django 5.0.2 on 2024-02-28 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0012_remove_node_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_domain_id',
        ),
        migrations.RemoveField(
            model_name='node',
            name='site_route_id',
        ),
    ]
