# Generated by Django 5.0.2 on 2024-02-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0012_rename_port_number_port_entry_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='port_app_id',
        ),
        migrations.AddField(
            model_name='port',
            name='port_app_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
