# Generated by Django 5.0.2 on 2024-02-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0013_remove_node_hostname_remove_node_node_domain_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
