# Generated by Django 5.0.2 on 2024-02-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0013_remove_node_port_app_id_port_port_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='application_type',
        ),
    ]
