# Generated by Django 5.0.2 on 2024-02-19 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0014_remove_node_application_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='exit_port',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8000)]),
        ),
    ]
